# Config file for automatic testing at travis-ci.org

language: python

install:
    - pip install tox
    - pip install -r requirements.txt

python:
    - "2.7"

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=pypy

# command to run tests, e.g. python setup.py test
script: tox
